import math

RES = WIDTH, HEIGHT = 1600, 900
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 60
PIXEL_SIZE = 100

# PLAYER
PLAYER_POSITION = 1.5, 5  # mini_map
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROTATION_SPEED = 0.002
PLAYER_SIZE_SCALE = 60

# MOUSE
MOUSE_SENSITIVITY = 0.0003
MOUSE_MAX_RELATIVE_MOVEMENT = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

# RAYCASTING
FIELD_OF_VIEW = math.pi / 3
HALF_FIELD_OF_VIEW = FIELD_OF_VIEW / 2
NUM_RAYS = WIDTH // 2  # // stands for integer division
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FIELD_OF_VIEW / NUM_RAYS
MAX_DEPTH = 20

# SCREEN
SCREEN_DISTANCE = HALF_WIDTH / math.tan(HALF_FIELD_OF_VIEW)
SCALE = WIDTH // NUM_RAYS

# FLOOR
FLOOR_COLOR = (30, 30, 30)

# TEXTURES
TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2
